# This file is autogenerated by the command `make fix-copies`, do not edit.
from ..utils import DummyObject, requires_backends


class ParrotSenseVoiceFeatureExtractor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["librosa", "scipy", "torch"])


class ParrotSenseVoiceProcessor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]


ParrotAudioFeatureExtractor = ParrotSenseVoiceFeatureExtractor
ParrotAudioProcessor = ParrotSenseVoiceProcessor

Parrot2AudioFeatureExtractor = ParrotSenseVoiceFeatureExtractor
Parrot2AudioProcessor = ParrotSenseVoiceProcessor
