# This file is autogenerated by the command `make fix-copies`, do not edit.
from transformers.utils import DummyObject, requires_backends


class ParrotAudioFeatureExtractor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["librosa", "scipy", "torch"])


class ParrotAudioProcessor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["librosa", "scipy", "torch"])


class ParrotSenseVoiceFeatureExtractor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["librosa", "scipy", "torch"])


class ParrotSenseVoiceProcessor(metaclass=DummyObject):
    _backends = ["librosa", "scipy", "torch"]
